# Generated by Django 2.2.6 on 2020-02-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=20)),
                ('code', models.CharField(blank=True, default='', max_length=10)),
                ('test_input', models.CharField(blank=True, default='', max_length=20)),
                ('test_output', models.CharField(blank=True, default='', max_length=20)),
                ('statement', models.TextField()),
            ],
        ),
    ]
